
# - name: Docker Package Registry
#   uses: craftech-io/package-action@v3.1.0

name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
# env:
#   # Use docker.io for Docker Hub if empty
#   REGISTRY: registry.redcloud.land
#   # github.repository as <account>/<repo>
#   IMAGE_NAME: dovecot/dovecot 
#         # ${{ github.repository }}
  
jobs:

  build:

    runs-on: [ self-hosted ]

    steps:
    - uses: actions/checkout@v2
      name: Checkout repository
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dovecot/dovecot:$(date +%s)
      

    # Workaround: https://github.com/docker/build-push-action/issues/461
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

    # Login against a Docker registry except on PR
    # https://github.com/docker/login-action
    - name: Log into registry ${{ env.REGISTRY }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.REDCLOUD_TOKEN }}


#     # Extract metadata (tags, labels) for Docker
#     # https://github.com/docker/metadata-action
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          
#     # Build and push Docker image with Buildx (don't push on PR)
#     # https://github.com/docker/build-push-action
#     - name: Build and push Docker image
#       id: build-and-push
#       uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
#       with:
#         context: .
#         push: ${{ github.event_name != 'pull_request' }}
#         tags: ${{ steps.meta.outputs.tags }}
#         labels: ${{ steps.meta.outputs.labels }}
        
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        registry: registry.redcloud.land
        username: ${{ secrets.REDCLOUD_USER }}
        password: ${{ secrets.REDCLOUD_TOKEN }}
        
#     - name: Publish to RedCloud
#       uses: docker/build-push-action@v2
#       with:
#         push: true
#         tags: dovecot/dovecot:latest



    - name: Build and push
      uses: docker/build-push-action@v2.10.0
      with:
        push: true
        tags: registry.redcloud.land/dovecot/dovecot:latest
